package br.com.joaovitorqueiroz.footballapi.ui.matchscreen.domain.model

import java.io.Serializable

enum class Stage(val value: String) : Serializable {
    FINAL("FINAL"),
    THIRD_PLACE("THIRD PLACE"),
    SEMI_FINALS("SEMI FINALS"),
    QUARTER_FINALS("QUARTER FINALS"),
    LAST_16("LAST 16"),
    LAST_32("LAST 32"),
    LAST_64("LAST 64"),
    ROUND_4("ROUND 4"),
    ROUND_3("ROUND 3"),
    ROUND_2("ROUND 2"),
    ROUND_1("ROUND 1"),
    GROUP_STAGE("GROUP STAGE"),
    PRELIMINARY_ROUND("PRELIMINARY ROUND"),
    QUALIFICATION("QUALIFICATION"),
    QUALIFICATION_ROUND_1("QUALIFICATION ROUND 1"),
    QUALIFICATION_ROUND_2("QUALIFICATION ROUND 2"),
    QUALIFICATION_ROUND_3("QUALIFICATION ROUND 3"),
    PLAYOFF_ROUND_1("PLAYOFF ROUND 1"),
    PLAYOFF_ROUND_2("PLAYOFF ROUND 2"),
    PLAYOFFS("PLAYOFFS"),
    REGULAR_SEASON("REGULAR SEASON"),
    CLAUSURA("CLAUSURA"),
    APERTURA("APERTURA"),
    CHAMPIONSHIP("CHAMPIONSHIP"),
    RELEGATION("RELEGATION"),
    RELEGATION_ROUND("RELEGATION ROUND"),
}
